import type { TeamRole } from '../model/types';

export const teamRoles: TeamRole[] = [
  {
    badge: 'PM',
    location: '서울',
    experience: '7년+',
    title: '프로젝트 매니저',
    job: '기획 · 일정 · 커뮤니케이션',
    strength: '요구사항 정리, 범위 조율',
    projectExperience: 'B2B 업무 시스템 / 외주 프로젝트',
    tags: ['기획', '문서화', '커뮤니케이션'],
    cursorText: 'PM',
  },
  {
    badge: 'FE',
    location: '경기',
    experience: '5년+',
    title: '프론트엔드 개발',
    job: '웹 화면 · 상태 관리 · 인터랙션',
    strength: '사용성 높은 화면 구조',
    projectExperience: '관리자, 대시보드, 현장 업무 UI',
    tags: ['React', 'TypeScript', 'TanStack'],
    cursorText: 'FE',
  },
  {
    badge: 'BE',
    location: '서울',
    experience: '6년+',
    title: '백엔드 개발',
    job: 'API · 데이터 · 권한 구조',
    strength: '안정적인 서비스 로직',
    projectExperience: 'ERP, 주문, 재고, 인증 시스템',
    tags: ['Node.js', 'Spring', 'SQL'],
    cursorText: 'BE',
  },
  {
    badge: 'APP',
    location: '서울',
    experience: '4년+',
    title: '모바일 개발',
    job: '현장 앱 · 스캐너 · 사진 업로드',
    strength: '실사용 환경에 맞는 앱 흐름',
    projectExperience: '배송, 검수, 설치, 점검 앱',
    tags: ['Expo', 'Kotlin', 'iOS'],
    cursorText: 'APP',
  },
  {
    badge: 'OPS',
    location: '경기',
    experience: '5년+',
    title: '운영·인프라',
    job: '배포 · 모니터링 · 장애 대응',
    strength: '운영 가능한 배포 환경',
    projectExperience: 'Nginx, PM2, SSL, 서버 운영',
    tags: ['Docker', 'Nginx', 'CI/CD'],
    cursorText: 'OPS',
  },
  {
    badge: 'UX',
    location: '부산',
    experience: '4년+',
    title: 'UI/UX 설계',
    job: '화면 구조 · 디자인 시스템',
    strength: '복잡한 기능의 쉬운 흐름화',
    projectExperience: '랜딩, 관리자, 디자인 시스템',
    tags: ['Figma', 'Prototype', 'Design System'],
    cursorText: 'UX',
  },
];
